# Tomcat 10 (Java 17)
FROM tomcat:10.1-jdk17-temurin-jammy

# 初期アプリを削除
RUN rm -rf /usr/local/tomcat/webapps/*

# 階層を一段上げた前提の設定
# プロジェクト直下に src があるならこれでOK
COPY ./src/main/webapp /usr/local/tomcat/webapps/ROOT

# コンパイル済みのクラスファイルをコピー
# ※GitHub上に build/classes フォルダが存在することを確認してください
COPY ./build/classes /usr/local/tomcat/webapps/ROOT/WEB-INF/classes

EXPOSE 8080
CMD ["catalina.sh", "run"]