# 1. 土台の用意
FROM tomcat:10.1-jdk17-temurin-jammy

# 2. 初期ファイルを消す
RUN rm -rf /usr/local/tomcat/webapps/*

# 3. 画面ファイルをコピー
# もしエラーが出る場合は ./src/main/webapp を ./WebContent に変えてみてください
COPY ./src/main/webapp /usr/local/tomcat/webapps/ROOT

# 4. Javaのクラスファイルをコピー
# Eclipseが作ったクラスファイルをTomcatの指定場所に置く
COPY ./build/classes /usr/local/tomcat/webapps/ROOT/WEB-INF/classes

EXPOSE 8080
CMD ["catalina.sh", "run"]